HEADER:
  label: "About me"

PRESENTATION:
  description: | "As a recent graduate with a strong passion for Digital Marketing, I'm excited to contribute to like-minded individuals and forward-thinking team. Looking to bring my enthusiasm and strong work ethic to collaborative and innovative projects."

SKILLS:
  enabled: true
  label: "Soft Skills"
  items:
    - title: "Teamwork"
    - title: "Adaptability"
    - title: "Fast Learner "
    - title: "Communication "
    - title: "Problem Solving "
      
