HEADER:
  label: "Volunteer Work and Project"

Volunteering:
  enabled: true
  label: "Experience"
  items:
    - period: "2023 — 2024"
      position: "Citizen Consumer Club Secretary at St Joseph’s College for Women"
      description: "Conducted various programmes and interactive sessions for students to raise consumer awareness and collaborated with academic social sectors."

 Project:
  enabled: true
  - title: "Importance of Financial Planning for Young Adults"
    description: "Researched on the factors influencing financial choices among young adults, providing strategic guidance & tips for improved financial education."

Online Presence :
  enabled: true
  - title: "Sharing fun, tips and inspiring contents"
    description: "Instagram: 6,000+ Followers"
    description: "Youtube: 300+ Subscribers"
