HEADER:
  label: "Contact"

Let's Connect: "I'm always interested in meeting like-minded individuals. Please feel free to contact me."

FORM:
  label: "Contact Form"
  fields:
    - name: "Full name"
    - email: "Email address"
    - message: "Your message"
    - submit: "Send message"
