# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Digital Marketing Enthusiast"
  name: "Nivetha N"
  username: "nivetha-n17" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/my-avatar.png"

INFO:
  - label: "Email"
    value: "nivetha.1782@gmail.com"
    icon: "mail-outline"
  - label: "Phone"
    value: "+91 8248698314"
    icon: "phone-portrait-outline"
  - label: "Birthday"
    value: "May 17, 2003"
    icon: "calendar-outline"
  - label: "Location"
    value: "Rakkiyapalayam, Kangeyam road, Tirupur"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-linkedin"
    url: "linkedin.com/in/~nivetha-n"
