HEADER:
  label: "Awards and Courses"

  - title: "First Prize in English Speech"
  - title: "Certified in Tally ERP essential Level 1"
  - title: "MS Office - Word, Excel, Powerpoint"
  - title: "Photoshop - Editing, Designing, Effects"
  - title: "Certified with 'A' under scheme for Capacity Building in Textile sector - Samarth"

HEADER:
  label: "Online Courses"

  - title: "Introduction to Digital Marketing - Great Learning"
  - description: "Enhanced in Digital Marketing fundamentals covering SEO, PPC and Social Media Marketing."
  - title: "SEO Principles : An Essential Guide for Beginners - Semrush Academy"
  - description: "Basic Knowledge of SEO, including Keyword Research,On-page optimization and Link Building."
  - title: "Social Media Marketing Crash Course - Semrush Academy"
  - description: "Understanding of SMM focusing on Content creation, Brand Awareness & Influencer Marketing"
