HEADER:
  label: "Qualifications"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2019 — 2020"
      institution: "Palaniammal Girls HR Sec School"
      description: "10th Grade - Passed out with 70%"
    - period: "2020 — 2021"
      institution: "Palaniammal Girls HR Sec School"
      description: "12th Grade - Passed out with 65%"
    - period: "2021 — 2024"
      institution: "St Joseph’s College for Women, Tirupur"
      description: "BCOM - Passed out with 80%"
    
VOLUNTEERING:
  enabled: true
  label: "Experience"
  items:
    - period: "2023 — 2024"
      position: "Citizen Consumer Club Secretary at St Joseph’s College for Women"
      description: "Conducted various programmes and interactive sessions for students to raise consumer awareness and collaborated with academic social sectors."
      
SKILLS:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "Tally"
    - skill: "Canva"
    - skill: "MS Office"
    - skill: "Communication"
    - skill: "Content Creation"
